
services:
  web:
    build: ./back
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5050:5050"
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
