name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: YourStrong!Passw0rd
          ACCEPT_EULA: Y
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build and run containers
        run: |
          docker-compose up
      
      - name: Wait for the database to be ready
        run: |
          sleep 10 # Дайте время базе данных запуститься
      
      - name: Test the API endpoint
        run: |
          curl http://localhost:5000/api || exit 1
      
      - name: Stop and remove containers
        run: docker-compose down
